name: Chemistry Dataset Analysis
description: Interactive analysis of student performance in chemistry exercises
url: https://username.github.io/chemistry-analysis

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: true
google_analytics: 
